### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by fiuipko** [Houfeng/react-finger#3]
Hello, I use your npm package, it works well, but when I import
```import { useFingerEvents } from "react-finger";```,
it works okay on dev, but then after page reload, I get:
```ReferenceError: navigator is not defined```,

and it then only works if I completely remove the import from my code.

**Comment by lioWeb1024** [comment]
俺也一样

**Comment by Houfeng** [comment]
> Hello, I use your npm package, it works well, but when I import `import { useFingerEvents } from "react-finger";`, it works okay on dev, but then after page reload, I get: `ReferenceError: navigator is not defined`,
> 
> and it then only works if I completely remove the import from my code.

Hi, @fiuipko 

Could you please provide the operating system and version, as well as the browser and version? Give me some information, I'll try to fix it.

**Comment by Houfeng** [comment]
> 俺也一样

@lioWeb1024 你好，
能提一下供操作系统和版本、以及浏览器和版本吗？给我一些信息，如果复现，我会尽快修复一下。

**Comment by lioWeb1024** [comment]
> > 俺也一样
> 
> @lioWeb1024 你好， 能提一下供操作系统和版本、以及浏览器和版本吗？给我一些信息，如果复现，我会尽快修复一下。

nextjs

**Comment by Houfeng** [comment]
> > > 俺也一样
> > 
> > 
> > @lioWeb1024 你好， 能提一下供操作系统和版本、以及浏览器和版本吗？给我一些信息，如果复现，我会尽快修复一下。
> 
> nextjs

@lioWeb1024  是有运行于 Server 端的 SSR 场景吗？ 目前在 SSR 场景还不能使用，近期会尝试支持一下

**Comment by Houfeng** [comment]
@lioWeb1024  可试一下最新版本 v2.2.7
@fiuipko  Try the latest version v2.2.7
